CREATE TABLE customer (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    name VARCHAR(225) NOT NULL,
    document VARCHAR(225) NOT NULL,
    phone VARCHAR(225) NOT NULL,
    email VARCHAR(70) NOT NULL,
    addressId BIGINT UNSIGNED,
    isInactive BOOLEAN DEFAULT FALSE,

FOREIGN KEY(addressId) REFERENCES address(id),
PRIMARY KEY(id));